# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.filename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('schedule', models.TextField(max_length=1000)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('subject_name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('location', models.TextField(max_length=200)),
                ('contact', models.TextField(max_length=1000)),
                ('number_of_students', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('subject_name',),
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('country_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.filename.RandomFileName('photos'))),
                ('is_active', models.BooleanField(default=True)),
                ('is_it_verified', models.BooleanField(default=False)),
                ('apply_course', models.ManyToManyField(related_name='apply_course', to='main.Course')),
                ('fav_announcement', models.ManyToManyField(related_name='favorite_announcement', to='main.Announcement')),
                ('fav_course', models.ManyToManyField(related_name='fav_course', to='main.Course')),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('has_branch', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('has_branch',),
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('verification_code', models.IntegerField()),
            ],
            options={
                'ordering': ('phone_number',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ('subject_name',),
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('about', models.TextField(max_length=1000)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=main.filename.RandomFileName('certificates'))),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.filename.RandomFileName('photos'))),
                ('address', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_it_verified', models.BooleanField(default=False)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.Subject')),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_in_organization', to='main.Tutor'),
        ),
        migrations.AddField(
            model_name='learner',
            name='fav_tutor',
            field=models.ManyToManyField(related_name='fav_tutor', to='main.Tutor'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to='main.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_in_courses', to='main.Tutor'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_created', to='main.Subject'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_in_announcement', to='main.Tutor'),
        ),
    ]
