# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tutor',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='tutor',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
